### ISSUE TITLE
media group

### ISSUE THREAD

**Issue by m2k7m** [KurimuzonAkuma/pyrogram#102]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hi, I'm having issue with all methods that deal with media group, i find out that its mainly because of get_media_group

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e85c5ad8-886c-4525-bf35-3f576e4d568d)

### Code example

```python
from pyrogram import Client
from pyrogram.types import Message

app = Client("testbot")

@app.on_message()
async def message(c: Client, m: Message):
    
    mideas = await c.get_media_group(6587576579,69710)
    print(mideas)

app.run()
```

### Logs

```shell
The message doesn't belong to a media group
Traceback (most recent call last):
  File "C:\Users\ALMWSHOOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\dispatcher.py", line 313, in handler_worker
    await handler.callback(self.client, *args)
  File "f:\Mahdi\Python\TestBot\youtube.py", line 11, in extract_audio
    mideas = await c.get_media_group(6587576579,69710)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALMWSHOOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrogram\methods\messages\get_media_group.py", line 73, in get_media_group
    raise ValueError("The message doesn't belong to a media group")
ValueError: The message doesn't belong to a media group
```

**Comment by m2k7m** [comment]
i also tried to get_message
```shell
{
    "_": "Message",
    "id": 69710,   
    "empty": true  
}
```
