### ISSUE TITLE
Error on get_chat caused by pinned messages

### ISSUE THREAD

**Issue by barbamento** [KurimuzonAkuma/pyrogram#44]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I found a single chat where the pinned messages has, for some reason unknown to me, a wrong id.

The problem is that, for that reason I'm unable to interact with the chat. It is possible to use a try except block for the pinned message retrieval?

### Steps to reproduce

I simply get this error using the get chat on a chat called "vezzoblog". Up until now it's the only chat i had this problem

### Code example

```python
from pyrogram import Client

app=Client(...)

with app:
        app.get_chat("vezzoblog")
```

### Logs

```shell
Traceback (most recent call last):
  File "mydir/test_pyrogram.py", line 56, in <module>
    app.get_chat("vezzoblog")
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/methods/chats/get_chat.py", line 87, in get_chat
    return await types.Chat._parse_full(self, r)
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/types/user_and_chats/chat.py", line 511, in _parse_full
    parsed_chat.pinned_message = await client.get_messages(
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/methods/messages/get_messages.py", line 117, in get_messages
    messages = await utils.parse_messages(self, r, replies=replies)
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/utils.py", line 155, in parse_messages
    reply_messages = await client.get_messages(
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/methods/messages/get_messages.py", line 115, in get_messages
    r = await self.invoke(rpc, sleep_threshold=-1)
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 94, in invoke
    r = await session.invoke(
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/session/session.py", line 399, in invoke
    return await self.send(query, timeout=timeout)
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/session/session.py", line 367, in send
    RPCError.raise_it(result, type(data))
  File "/.cache/pypoetry/virtualenvs/envname/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdsEmpty: Telegram says: [400 MESSAGE_IDS_EMPTY] - The requested message doesn't exist or you provided no message id (caused by "channels.GetMessages")
```

**Comment by 0xWEBMILK** [comment]
Hello! the <.get_chat()> method you are using takes the argument “vezzoblog”. Try passing the id of the chat in the arguments instead of its nickname

More information at: https://docs.pyrogram.org/api/methods/get_chat

```
Parameters:
chat_id (int | str) – Unique identifier (int) or username (str) of the target chat. Unique identifier for the target chat in form of a t.me/joinchat/ link, identifier (int) or username of the target channel/supergroup (in the format @username).
```

**Comment by KurimuzonAkuma** [comment]
Should be fixed in c834f4ce7ec1cca0ff66a44fe1c987ca18d72804

**Comment by vraixen** [comment]
i don't know if this is fixed but when i try to use get chat with force_full true i get an exeption when there's no pinned message.
The point is that i use get chat to avoid making multiple requests to get subs number and other infos.

`chat = await app_bot.get_chat(channel_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/methods/chats/get_chat.py", line 93, in get_chat return await types.Chat._parse_full(self, r) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/types/user_and_chats/chat.py", line 1261, in _parse_full return await Chat._parse_full_channel(client, chat_full.full_chat, users, chats) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/types/user_and_chats/chat.py", line 1186, in _parse_full_channel parsed_chat.pinned_message = await client.get_messages(chat_id=parsed_chat.id, pinned=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/methods/messages/get_messages.py", line 136, in get_messages messages = await utils.parse_messages(self, r, replies=replies) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/utils.py", line 191, in parse_messages reply_messages = await client.get_messages( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/methods/messages/get_messages.py", line 134, in get_messages r = await self.invoke(rpc, sleep_threshold=-1) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 107, in invoke r = await session.invoke( ^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 551, in invoke return await self.send(query, timeout=timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 514, in send RPCError.raise_it(result, type(data)) File "/root/KokoroNetworkBot/.venv/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it raise getattr( pyrogram.errors.exceptions.bad_request_400.MessageIdsEmpty: Telegram says: [400 MESSAGE_IDS_EMPTY] - The requested message doesn't exist or you provided no message id. (caused by "channels.GetMessages")`

**Comment by KurimuzonAkuma** [comment]
> i don't know if this is fixed but when i try to use get chat with force_full true i get an exeption when there's no pinned message. The point is that i use get chat to avoid making multiple requests to get subs number and other infos.

Cant reproduce this error. Fork version?

**Comment by vraixen** [comment]
i'm using the pip version
