### ISSUE TITLE
download_media(), the file size equals to 0 B

### ISSUE THREAD

**Issue by fivepe** [KurimuzonAkuma/pyrogram#62]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

When downloading photo or video, sometimes some files have a size of 0 or are incomplete after downloading.

### Steps to reproduce

download photos, some photo is 0 size.
![image](https://github.com/KurimuzonAkuma/pyrogram/assets/131561603/5403881a-1efb-44b3-a4f9-abe5de8fccf9)

### Code example

```python
file = await app.download_media(msg, file_name=filename_temp, progress=progress, progress_args=(download_msg,))
```

### Logs

```shell
[10] Retrying "upload.GetFile" due to: Request timed out
Request timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 971, in get_file
    r = await session.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 422, in invoke
    return await self.invoke(query, retries - 1, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 422, in invoke
    return await self.invoke(query, retries - 1, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 422, in invoke
    return await self.invoke(query, retries - 1, timeout)
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 412, in invoke
    raise e from None
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 399, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 361, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out
```

**Comment by Yash126116** [comment]
Same error

**Comment by DevVastavikRahul** [comment]
pyrogram.session.auth: Retrying due to KeyError: 0
2025-09-09T07:05:40.167321+00:00 app[worker.1]: [ INFO/2025-09-09 07:05:40,167] pyrogram.connection.connection: Disconnected
2025-09-09T07:05:40.167379+00:00 app[worker.1]: [ INFO/2025-09-09 07:05:40,167] pyrogram.session.auth: Start creating a new auth key on DC4
2025-09-09T07:05:40.167426+00:00 app[worker.1]: [ INFO/2025-09-09 07:05:40,167] pyrogram.connection.connection: Connecting...
2025-09-09T07:05:40.251715+00:00 app[worker.1]: [ INFO/2025-09-09 07:05:40,251] pyrogram.connection.connection: Connected! Production DC4 - IPv4


❌ Failed to save: https://t.me/c/2342059864/1321

Error: File size equals to 0 B

**Comment by mike89klein** [comment]
When comparing the work of pyrogram and kurigram with active proxy variable, it seems that the problem lies in the proxy module, the tcp_abridged.py file, but I can’t figure out what exactly it is yet.
