### ISSUE TITLE
[420 FLOOD_PREMIUM_WAIT_X] While Uploading video

### ISSUE THREAD

**Issue by arkaroy14** [KurimuzonAkuma/pyrogram#68]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am trying to upload video but i am getting lots of [420 FLOOD_PREMIUM_WAIT_X] message, terminal getting full, so its difficult to check output.

### Steps to reproduce

If i use progress_callback then only this spamming messages showing.
I just want to hide spam with using progress_callback

### Code example

```python
client.send_video(chat_id=username, reply_to_message_id=forum_id, video=video_path, caption=caption, progress=progress_callback, thumb=thumbnail_path, duration=int(duration), supports_streaming=True)
```

### Logs

```shell
  0% 0.00/126M [00:00<?, ?B/s]Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 12 seconds is required (caused by "upload.SaveBigFilePart")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 399, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 367, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodPremiumWait: Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 12 seconds is required (caused by "upload.SaveBigFilePart")
```

**Comment by PunchEnergyFTW** [comment]
I am experiencing the same issue. Once my upload has "finished", meaning all bytes were uploaded somewhere to telegram's servers, the process will just hang indefinetly.

**Comment by Cosmos-Break** [comment]
same here, use telethon can solve the problem

**Comment by Cosmos-Break** [comment]
Just let telethon handle the flood wait, this is my code:
```
from telethon import TelegramClient
vid_path = sys.argv[1]
client = TelegramClient('test_telethon', tg_api_id, tg_api_hash)
client.start()
client.send_file('me', vid_path)
client.disconnect()
```


It returns:
```
2024-06-07 08:58:55,492 | INFO | Using TgCrypto
2024-06-07 08:58:56,048 | INFO | libssl detected, it will be used for encryption
2024-06-07 08:58:57,764 | INFO | Connecting to 91.108.56.133:443/TcpFull...
2024-06-07 08:58:57,845 | INFO | Connection to 91.108.56.133:443/TcpFull complete!
2024-06-07 08:58:58,379 | INFO | Uploading file of 247711036 bytes in 945 chunks of 262144
2024-06-07 08:59:08,615 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
2024-06-07 08:59:24,314 | INFO | Sleeping for 7s (0:00:07) on SaveBigFilePartRequest flood wait
2024-06-07 08:59:42,313 | INFO | Sleeping for 5s (0:00:05) on SaveBigFilePartRequest flood wait
2024-06-07 08:59:57,316 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
2024-06-07 09:00:14,140 | INFO | Sleeping for 5s (0:00:05) on SaveBigFilePartRequest flood wait
2024-06-07 09:00:32,593 | INFO | Sleeping for 3s (0:00:03) on SaveBigFilePartRequest flood wait
2024-06-07 09:00:48,437 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
2024-06-07 09:01:07,598 | INFO | Sleeping for 3s (0:00:03) on SaveBigFilePartRequest flood wait
2024-06-07 09:01:23,117 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
2024-06-07 09:01:39,126 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
2024-06-07 09:01:53,316 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
2024-06-07 09:02:11,517 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
2024-06-07 09:02:25,717 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
2024-06-07 09:02:42,540 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
2024-06-07 09:03:01,297 | INFO | Sleeping for 3s (0:00:03) on SaveBigFilePartRequest flood wait
2024-06-07 09:03:47,966 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
2024-06-07 09:04:04,825 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
2024-06-07 09:04:20,825 | INFO | Disconnecting from 91.108.56.133:443/TcpFull...
2024-06-07 09:04:20,825 | INFO | Disconnection from 91.108.56.133:443/TcpFull complete!

```

**Comment by arkaroy14** [comment]
@Cosmos-Break my problem with telethon is, 
1) very slow speed compared to pyrogram which gives around 7-15+ MBPS sometimes even 40 MBPS. 
2) I already implemented large based portion of my code using pyrogram now switching to telethon everywhere seems lots of extra task. 
3) I used TgCrypto along with pyrogram so speed is very good there but i am not able to use it along with telethon. If u can share TgCrypto package u use for telethon i can also test speed and compare. 

What i feel if telethon can handle it properly pyrogram should also able to handle "SaveBigFilePartRequest" flood properly. 

As this project seems little bit updated than orginal pyrogram so i thought someone can help with source code to fix this issue and handle FloodWait properly.

Anyway i will try to find in telethon code how this type of flood wait is handling properly. Thanks for your detailed reply.

**Comment by Cosmos-Break** [comment]
I checked code of pyrogram before, It uses 4 workers to upload large file, maybe it is the reason of pyrogram's high upload speed.

**Comment by PunchEnergyFTW** [comment]
> Just let telethon handle the flood wait, this is my code:
> 
> ```python
> from telethon import TelegramClient
> vid_path = sys.argv[1]
> client = TelegramClient('test_telethon', tg_api_id, tg_api_hash)
> client.start()
> client.send_file('me', vid_path)
> client.disconnect()
> ```
> 
> It returns:
> 
> ```
> 2024-06-07 08:58:55,492 | INFO | Using TgCrypto
> 2024-06-07 08:58:56,048 | INFO | libssl detected, it will be used for encryption
> 2024-06-07 08:58:57,764 | INFO | Connecting to 91.108.56.133:443/TcpFull...
> 2024-06-07 08:58:57,845 | INFO | Connection to 91.108.56.133:443/TcpFull complete!
> 2024-06-07 08:58:58,379 | INFO | Uploading file of 247711036 bytes in 945 chunks of 262144
> 2024-06-07 08:59:08,615 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
> 2024-06-07 08:59:24,314 | INFO | Sleeping for 7s (0:00:07) on SaveBigFilePartRequest flood wait
> 2024-06-07 08:59:42,313 | INFO | Sleeping for 5s (0:00:05) on SaveBigFilePartRequest flood wait
> 2024-06-07 08:59:57,316 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:00:14,140 | INFO | Sleeping for 5s (0:00:05) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:00:32,593 | INFO | Sleeping for 3s (0:00:03) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:00:48,437 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:01:07,598 | INFO | Sleeping for 3s (0:00:03) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:01:23,117 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:01:39,126 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:01:53,316 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:02:11,517 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:02:25,717 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:02:42,540 | INFO | Sleeping for 6s (0:00:06) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:03:01,297 | INFO | Sleeping for 3s (0:00:03) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:03:47,966 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:04:04,825 | INFO | Sleeping for 4s (0:00:04) on SaveBigFilePartRequest flood wait
> 2024-06-07 09:04:20,825 | INFO | Disconnecting from 91.108.56.133:443/TcpFull...
> 2024-06-07 09:04:20,825 | INFO | Disconnection from 91.108.56.133:443/TcpFull complete!
> ```

Doesn't work for me. 
First of all i had to make some changes to make this snippet run properly. Here's my code:
```py
from telethon import TelegramClient
import sys
api_id = ''
api_hash = ''

async def send_video(vid_path):
    await client.start()
    await client.send_file('me', vid_path)
    await client.disconnect()

if __name__ == '__main__':
    client = TelegramClient('telethon-custom', api_id, api_hash)
    vid_path = sys.argv[1]
    client.loop.run_until_complete(send_video(vid_path))
```


vid_path is my 2000MiB "blob" file again.

here the output:
```bash
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.loop.run_until_complete(send_video(vid_path))
  File "/home/PunchEnergyFTW/.local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 9, in send_video
    await client.send_file('me', vid_path)
  File "/telethon_venv/lib/python3.8/site-packages/telethon/client/uploads.py", line 408, in send_file
    file_handle, media, image = await self._file_to_media(
  File "/telethon_venv/lib/python3.8/site-packages/telethon/client/uploads.py", line 744, in _file_to_media
    file_handle = await self.upload_file(
  File "/telethon_venv/lib/python3.8/site-packages/telethon/client/uploads.py", line 678, in upload_file
    result = await self(request)
  File "/telethon_venv/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/telethon_venv/lib/python3.8/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.FloodError: RPCError 420: FLOOD_PREMIUM_WAIT_7 (caused by SaveBigFilePartRequest)
```

**Comment by Cosmos-Break** [comment]
Telegram premium solves everything.

**Comment by PunchEnergyFTW** [comment]
> Telegram premium solves everything.

Which sadly is not availiable in Germany

**Comment by doublep21** [comment]
the issue is the new Flood_Premium_wait error , in the code there is nothing that can handle the wait and then continue . i found a way to get it work with telethon but i need pyrogram🥲

**Comment by ndyanx** [comment]
> Telegram premium solves everything.

Absolutely, Telegram Premium effectively resolves all the mentioned issues.

**Comment by arkaroy14** [comment]
Can anyone check by modifying below portion

https://github.com/KurimuzonAkuma/pyrogram/blob/7377290383cc9a6034000e6e111093ef8d5667f0/pyrogram/methods/advanced/save_file.py#L108

Replace, 
`
try:
                        await session.invoke(data)
                    except Exception as e:
                        log.exception(e)
`
With, 
`
try:
                        await session.invoke(data)
                    except pyrogram.errors.exceptions.flood_420.FloodPremiumWait: 
                        raise
                    except Exception as e:
                        log.exception(e)
`

Now try to catch the exact exception in your code it should able to catch wait, 
`except pyrogram.errors.exceptions.flood_420.FloodPremiumWait
`

**Comment by GenocideStomper** [comment]
I still have this issue in v2.1.37, at least with send_media_group(). I've tried putting a try-except construct around it like in https://docs.kurigram.live/faq/how-to-avoid-flood-waits/, however it makes no difference and I still have the issue of the script crashing:


```
[my_account] Waiting for 8 seconds before continuing (required by "upload.SaveFilePart")
Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 15 seconds is required (caused by "upload.SaveFilePart")
Traceback (most recent call last):
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/session/session.py", line 406, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/session/session.py", line 374, in send
    RPCError.raise_it(result, type(data))
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.flood_420.FloodPremiumWait: Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 15 seconds is required (caused by "upload.SaveFilePart")
Traceback (most recent call last):
  File "/home/user/kurigram.py", line 55, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/kurigram.py", line 48, in main
    await app.send_media_group(
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/methods/messages/send_media_group.py", line 214, in send_media_group
    media = await self.invoke(
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 94, in invoke
    r = await session.invoke(
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/session/session.py", line 406, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/session/session.py", line 374, in send
    RPCError.raise_it(result, type(data))
  File "/home/user/kurigram/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.FilePartMissing: Telegram says: [400 FILE_PART_X_MISSING] - Part 0 of the file is missing from storage (caused by "messages.UploadMedia")
```
